### PR TITLE
Symfony upgrades

### PR DESCRIPTION
**Pull request by Klap-in**
* [x] Upgrade to 3, 
 * [x] Upgrade to 4.4
 * [x] Upgrade to 5.4
 * [ ] ~Upgrade to 6.2?~
https://symfony.com/releases

The upgrades include a lot of changes to the structure of the project.

- Due to rename of classes all cached/serialized objects will break. So temporary backported.
- There were some database changes. Also introduces Doctrine Migrations, which let you create queries per change of the database, these can be applied on production.
- Not yet updated to 6.2, as it requires higher than php 7.4. Fixed a couple of bugs, see the commits.
- Introduced merge request on GitLab. Not implemented for Bitbucket, because personal access tokens are only available for the payed variant. Implementing OAuth for Bitbucket is considered as too much work for the only 10 to 20 repositories that are now hosted on Bitbucket, see #114 .

After update, 

For deploying:
 - [x] create GitLab account
   - [x] create api personal access key
 - [x] backups database, data folder, old configs, etc
 - [x] pull new code from git
 - [x] create `.env.local` (uncommitted) from `.env` (committed) configuration file at top level. Based on the old config in `app/config/parameters.yml`. 
 - [x] composer update
 - [ ] consider to use `composer dump-env prod`, this created a parsed `.env.local.php` which loaded instead of the cascaded .env files. Gives a bit performance improvement, but can be overlooked when modifying the .env.local...
 - [x] migrate database [wiki/Deploying-production](https://github.com/dokufreaks/dokuwiki-translation/wiki/Deploying-production)  and [wiki/Doctrine](https://github.com/dokufreaks/dokuwiki-translation/wiki/Doctrine)
 - [x] javascript libraries must be retrieved from yarn 
   - [x] auto build and deploy javascript & css with Github Action, @splitbrain could you have a look on this?
 - [x] `dokuwiki:updateLanguages` to refresh local language objects
 - [x] test mail functionality
 
Futher:
 - [ ] test for unexpected stuff
   - [ ] forms
   - [ ] `dokuwiki:updateGit`, `dokuwiki:updateDwApi`
 - [ ] plugins/templates hosted at GitLab, needs to be deleted and readded via command line, such that a fork is created on GitLab. Use `dokuwiki:showInfo basicinfo` for a list of all repos, output can be used in the `dokuwiki:addRepo` command.

### CODE REVIEW

**Comment by Klap-in** [comment]
@splitbrain Symfony 5 will introduces support for separate handling of secrets. It could have an advantage for swapping out the local/development settings with the productions settings, and that the production setting can be already added and prepared at the development machine. However, it needs also managing another private key for the production version. While at the end of course the secrets are accessible as usual on the production machine. At the moment the production machine is also the only place that knows them.
Some explaination: https://symfonycasts.com/screencast/symfony5-upgrade/secrets-vault-setup and following pages.

My stance now is not to introduce the such a vault, or do you see advantages for us that I overlooked?

**Comment by Klap-in** [comment]
Exactly.

Do you like to move this repro to the dokuwiki organization at certain point as well? 
Like the plugin wizard you are moving and combining now 👍 .

**Comment by Klap-in** [comment]
@splitbrain I introduce also Webpack Encore. This uses yarn etc. 
Do you have preference how to deploy? Is building on the server fine for you? Needs install of node.js /node_modules on the server. 
I’m still looking if there is simple way to build locally and then getting it to the server. Due to regular changing file names committing all build files is not recommended in general. However, maybe do to the low frequency it is more pragmatic to ignore that for us. Then I have only to check how I switching between dev and prod is handled by git, but maybe a .gitignore is enough.
https://symfony.com/doc/4.4/frontend.html#encore-toc
https://symfony.com/doc/4.4/frontend/encore/faq.html#how-do-i-deploy-my-encore-assets

**Comment by splitbrain** [comment]
> Do you like to move this repro to the dokuwiki organization at certain point as well

Yes, ultimately I'd like to have all the infrastructure projects in the organization.

>  introduce also Webpack Encore. This uses yarn etc.

That's fine, I have some experience using yarn. I think the best approach will be to implement automatic build and deploy via github actions. I can have a look at this once you're done.

**Comment by splitbrain** [comment]
I'm currently relying on the PHP provided by Debian which is still 7.4 so keeping 7.4 compatibility makes things easier for now. But there are ways to run a newer PHP so if need be we can get it running.

**Comment by Klap-in** [comment]
Hi @splitbrain 
I think this code should be in workable state. Due to the amount of changes/upgrades I cannot image everything is perfect, but it brings it to a more recent base, based on symfony 5.4, to continue.

How could we perform this upgrade on the server?
Is that something you like to do, or should I try? I guess you have a bit more experience there...
I made a checklist in the start post of this PR to collect some of the main things.
You proposed to use GitHub Actions for building and deploying the js and css via yarn/node.js. Do you have the possibility to have a look in to that?

**Comment by splitbrain** [comment]
Awesome! Thank you very much for all the work you put into this. I will look into the deployment process, but it might be a couple of weeks til I have the time.

One more question. Do you think it would be possible to run the whole thing on top of sqlite instead of mysql? Does not need to happen right away, but in general I find sqlite adequate enough for most applications and much easier to handle... not sure if symfony supports it though

**Comment by Klap-in** [comment]
> Awesome! Thank you very much for all the work you put into this. I will look into the deployment process, but it might be a couple of weeks til I have the time.

Fine for me. We are not in hurry.

> 
> One more question. Do you think it would be possible to run the whole thing on top of sqlite instead of mysql? Does not need to happen right away, but in general I find sqlite adequate enough for most applications and much easier to handle... not sure if symfony supports it though

Symfony/Doctrine supports SQLite.
https://symfony.com/doc/current/doctrine.html#configuring-the-database
https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/configuration.html
But I expect we possibly need to update the entities a bit (SQLite has less data types) and the queries. For development MySQL works for me, but if you prefer SQLite, I think it is doable to switch over. Which advantage are you looking for in the Translation tool?

**Comment by Klap-in** [comment]
Hi Andi,
It is almost an half year ago, but I was wondering how we can bring this further. My feeling is that how longer we waits, how more I forget about the details ;-) however, I'm also a bit less flexible with availability. So I was wondering if you expect to have some time  available for deploying this? Probably, handy to align a bit, such that I can help fixing things that we discover during such attempt.

**Comment by splitbrain** [comment]
Damn, you're right! We really need to get this online. Unfortunately I'm leaving tomorrow morning, so this has to wait til next week. Probably wednesday evening earliest. I'll put it on my calendar.

**Comment by splitbrain** [comment]
I'm stuck with the migrations currently:

```
[error] Migration DoctrineMigrations\Version20230414172519 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1832 Cannot change column 'language': used in a foreign key constraint 'translate/FK_F9AAD2F9D4DB71B5'"
```

**Comment by splitbrain** [comment]
I'm unsure how to proceed. The problem is caused by the change in mariaDB no longer supporting the disabling of foreign key checks on collation changes. Instead we would need to drop the contraints and readd them. But constraints can only be dropped by name and those names have been auto generated. So we would need to read the contraint names from the information schema... seems a lot of work.

The problem probably does not exist on the live server since it's running an older MariaDB version than my local setup. So maybe I could ignore the issue. OTOH everyone developing on a fresh database (eg. not using a live server dump) will run into this problem in the future...

Shit like this is why I asked if we could switch to sqlite...

**Comment by splitbrain** [comment]
Ahh luckily our foreign keys were all created with fixed names. So the fix was easier.

**Comment by splitbrain** [comment]
@Klap-in I think I'm ready to deploy. I will have dinner now and continue in an hour or so. Could you please mail me the API key for gitlab? I will be available on IRC if you have time to chat...

**Comment by splitbrain** [comment]
And we're live. Everything seems to work so far. I was able to create a PR and to request an edit token by email.

Building and deployment happens via github action all the needed secrets are stored in github's secret vault and are written to env.local on deployment.

**Comment by Klap-in** [comment]
Nice! Thanks for deploying.
I will look up the gitlab credentials.

**Pull request merged**
